"""Initial migration

Revision ID: 902b727583b4
Revises:
Create Date: 2026-02-01 16:05:02.394134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "902b727583b4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('wrappers_fdw_stats')
    op.alter_column("categories", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(
        op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_user_category_name", "categories", ["user_id", "name"]
    )
    # op.alter_column('transactions', 'transaction_type',
    #            existing_type=postgresql.ENUM('expense', 'income', name='transactiontype'),
    #            type_=sa.Enum('expense', 'income', name='transaction_type_enum'),
    #            nullable=False)

    op.execute("""
    ALTER TABLE transactions
    ALTER COLUMN transaction_type
    TYPE transaction_type_enum
    USING transaction_type::text::transaction_type_enum
    """)
    # op.execute("""
    # ALTER TABLE transactions
    # ALTER COLUMN transaction_type
    # TYPE transaction_type_enum
    # USING transaction_type::transaction_type_enum
    # """)
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )
    op.create_index(
        op.f("ix_transactions_category_id"),
        "transactions",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users",
        "current_balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "total_expenses",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "total_income",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.alter_column(
        "users",
        "total_income",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "total_expenses",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "current_balance",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "transaction_type",
        existing_type=sa.Enum("expense", "income", name="transaction_type_enum"),
        type_=postgresql.ENUM("expense", "income", name="transactiontype"),
        nullable=True,
    )
    op.drop_constraint("uq_user_category_name", "categories", type_="unique")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.alter_column("categories", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.create_table(
        "wrappers_fdw_stats",
        sa.Column("fdw_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "create_times",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Total number of times the FDW instacne has been created",
        ),
        sa.Column(
            "rows_in",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Total rows input from origin",
        ),
        sa.Column(
            "rows_out",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Total rows output to Postgres",
        ),
        sa.Column(
            "bytes_in",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Total bytes input from origin",
        ),
        sa.Column(
            "bytes_out",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Total bytes output to Postgres",
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Metadata specific for the FDW",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("fdw_name", name=op.f("wrappers_fdw_stats_pkey")),
        comment="Wrappers Foreign Data Wrapper statistics",
    )
    # ### end Alembic commands ###
